ptu12_library/library/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('authors/', views.author_list, name='author_list'),
    path('author/<int:pk>/', views.author_detail, name='author_detail'),
    path('books/', views.BookListView.as_view(), name='book_list'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('books/my/', views.UserBookInstanceListView.as_view(), name='user_book_instances'),
    path('book/reserve/', views.BookInstanceCreateView.as_view(), name='bookinstance_create'),
    path('book/take/<uuid:pk>/', views.BookInstanceUpdateView.as_view(), name='bookinstance_update'),
    path('book/return/<uuid:pk>/', views.BookInstanceDeleteView.as_view(), name='bookinstance_delete'),
]

ptu12_library/ptu12_library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('library.urls')),
    path('profile/', include('user_profile.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

ptu12_library/library/models.py
from django.contrib.auth import get_user_model
from datetime import date
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from tinymce.models import HTMLField
import uuid

User = get_user_model()


class Genre(models.Model):
    name = models.CharField(_("name"), max_length=100)

    class Meta:
        verbose_name = _("genre")
        verbose_name_plural = _("genres")

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(_("first name"), max_length=50, db_index=True)
    last_name = models.CharField(_("last name"), max_length=50, db_index=True)
    biography = HTMLField(_("biography"), max_length=8000, blank=True, null=True)

    class Meta:
        ordering = ['last_name', 'first_name']
        verbose_name = _("author")
        verbose_name_plural = _("authors")

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("author_detail", kwargs={"pk": self.pk})

    def display_books(self):
        return ', '.join(book.title for book in self.books.all()[:3])
    display_books.short_description = _('books')


class Book(models.Model):
    title = models.CharField(_("title"), max_length=250, db_index=True)
    summary = HTMLField(_("summary"), max_length=4000)
    author = models.ForeignKey(
        Author, 
        verbose_name=_("author"), 
        on_delete=models.CASCADE,
        related_name='books',
    )
    genre = models.ManyToManyField(
        Genre, 
        verbose_name=_("genre(s)"), 
        help_text=_("choose genre(s) for this book")
    )
    cover = models.ImageField(
        _("cover"), 
        upload_to='library/book_covers', 
        null=True, 
        blank=True,
    )

    class Meta:
        ordering = ['title']
        verbose_name = _("book")
        verbose_name_plural = _("books")

    def __str__(self):
        return f"{self.author} - {self.title}"

    def get_absolute_url(self):
        return reverse("book_detail", kwargs={"pk": self.pk})

    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])
    display_genre.short_description = _('genre')


class BookInstance(models.Model):
    id = models.UUIDField(_("ID"), primary_key=True, default=uuid.uuid4)
    book = models.ForeignKey(
        Book, 
        verbose_name=_("book"), 
        on_delete=models.CASCADE,
        related_name='instances',
    )
    due_back = models.DateField(_("due back"), null=True, blank=True, db_index=True)
    reader = models.ForeignKey(
        User, 
        verbose_name=_("reader"), 
        on_delete=models.CASCADE,
        related_name='book_instances',
        null=True, blank=True,
    )

    STATUS_CHOICES = (
        (0, _('Available')),
        (1, _('Reserved')),
        (2, _('Taken')),
        (3, _('Unavailable')),
        (7, _('Broken')),
    )
    
    status = models.PositiveSmallIntegerField(
        _("status"), 
        choices=STATUS_CHOICES, 
        default=0,
        db_index=True
    )

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    class Meta:
        ordering = ['due_back']
        verbose_name = _("book instance")
        verbose_name_plural = _("book instances")

    def __str__(self):
        return f"{self.book.title} - {self.get_status_display()}"

    def get_absolute_url(self):
        return reverse("bookinstance_detail", kwargs={"pk": self.pk})


class BookReview(models.Model):
    book = models.ForeignKey(
        Book, 
        verbose_name=_("book"), 
        on_delete=models.CASCADE,
        related_name='reviews',
    )
    reviewer = models.ForeignKey(
        User, 
        verbose_name=_("reviewer"), 
        on_delete=models.SET_NULL,
        related_name='book_reviews',
        null=True, blank=True,
    )
    reviewed_at = models.DateTimeField(_("Reviewed"), auto_now_add=True)
    content = models.TextField(_("content"), max_length=4000)

    class Meta:
        ordering = ['-reviewed_at']
        verbose_name = _("book review")
        verbose_name_plural = _("book reviews")

    def __str__(self):
        return f"{self.reviewed_at}: {self.reviewer}"

    def get_absolute_url(self):
        return reverse("bookreview_detail", kwargs={"pk": self.pk})

ptu12_library/library/forms.py
from django import forms
from . import models


class DateInput(forms.DateInput):
    input_type = 'date'


class BookReviewForm(forms.ModelForm):
    class Meta:
        model = models.BookReview
        fields = ('content', 'book', 'reviewer')
        widgets = {
            'book': forms.HiddenInput(),
            'reviewer': forms.HiddenInput(),
        }


class BookInstanceForm(forms.ModelForm):
    class Meta:
        model = models.BookInstance
        fields = ('book', 'due_back', 'reader', 'status')
        widgets = {
            'book': forms.HiddenInput(),
            'reader': forms.HiddenInput(),
            'due_back': DateInput(),
            'status': forms.HiddenInput(),
        }

ptu12_library/library/views.py
from typing import Any, Dict, Optional
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.core.paginator import Paginator
from datetime import date, timedelta
from django.db.models.query import QuerySet
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views import generic
from . forms import BookReviewForm, BookInstanceForm
from . models import Book, Author, BookInstance, Genre

def index(request):
    # Suskaičiuokime keletą pagrindinių objektų
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    
    # Laisvos knygos (tos, kurios turi statusą 'g')
    num_instances_available = BookInstance.objects.filter(status__exact=0).count()
    
    # Kiek yra autorių    
    num_authors = Author.objects.count()

    # Apsilankymų skaitliukas
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1
    
    # perduodame informaciją į šabloną žodyno pavidale:
    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits,
    }

    return render(request, 'library/index.html', context)

def author_list(request):
    qs = Author.objects
    query = request.GET.get('query')
    if query:
        qs = qs.filter(
            Q(last_name__istartswith=query) |
            Q(first_name__icontains=query)
        )
    else:
        qs = qs.all()
    paginator = Paginator(qs, 5)
    author_list = paginator.get_page(request.GET.get('page'))
    return render(request, 'library/authors.html', {
        'author_list': author_list,
    })

def author_detail(request, pk: int):
    return render(request, 'library/author_detail.html', {
        'author': get_object_or_404(Author, pk=pk)
    })


class BookListView(generic.ListView):
    model = Book
    paginate_by = 6
    template_name = 'library/book_list.html'

    def get_queryset(self) -> QuerySet[Any]:
        qs = super().get_queryset()
        query = self.request.GET.get('query')
        if query:
            qs = qs.filter(
                Q(title__icontains=query) |
                Q(summary__icontains=query) |
                Q(author__last_name__istartswith=query)
            )
        return qs


class BookDetailView(generic.edit.FormMixin, generic.DetailView):
    model = Book
    template_name = 'library/book_detail.html'
    form_class = BookReviewForm

    def get_initial(self) -> Dict[str, Any]:
        initial = super().get_initial()
        initial['book'] = self.get_object()
        initial['reviewer'] = self.request.user
        return initial

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
        
    def form_valid(self, form: Any) -> HttpResponse:
        form.instance.book = self.get_object()
        form.instance.reviewer = self.request.user
        form.save()
        messages.success(self.request, _('Review posted!'))
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse('book_detail', kwargs={'pk':self.get_object().pk})


class UserBookInstanceListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'library/user_bookinstance_list.html'
    paginate_by = 10

    def get_queryset(self) -> QuerySet[Any]:
        qs = super().get_queryset()
        qs = qs.filter(reader=self.request.user)
        return qs


class BookInstanceCreateView(LoginRequiredMixin, generic.CreateView):
    model = BookInstance
    form_class = BookInstanceForm
    template_name = 'library/bookinstance_form.html'
    success_url = reverse_lazy('user_book_instances')

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['book'] = self.book
        return context

    def get_initial(self) -> Dict[str, Any]:
        self.book = get_object_or_404(Book, id=self.request.GET.get('book_id'))
        initial = super().get_initial()
        initial['book'] = self.book
        initial['reader'] = self.request.user
        initial['due_back'] = date.today() + timedelta(days=14)
        initial['status'] = 1
        return initial

    def form_valid(self, form):
        form.instance.book = self.book
        form.instance.reader = self.request.user
        form.instance.status = 1
        return super().form_valid(form)


class BookInstanceUpdateView(
    LoginRequiredMixin, 
    UserPassesTestMixin, 
    generic.UpdateView
):
    model = BookInstance
    form_class = BookInstanceForm
    template_name = 'library/bookinstance_form.html'
    success_url = reverse_lazy('user_book_instances')

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        obj = self.get_object()
        context['book'] = obj.book
        if obj.status == 1:
            context['taking'] = True
        else:
            context['extending'] = True
        return context

    def get_initial(self) -> Dict[str, Any]:
        initial = super().get_initial()
        initial['due_back'] = date.today() + timedelta(days=14)
        initial['status'] = 2
        return initial

    def form_valid(self, form):
        form.instance.reader = self.request.user
        form.instance.status = 2
        messages.success(self.request, _('Book now is taken or extended.'))
        return super().form_valid(form)

    def test_func(self) -> bool | None:
        obj = self.get_object()
        return obj.reader == self.request.user


class BookInstanceDeleteView(
    LoginRequiredMixin,
    UserPassesTestMixin,
    generic.DeleteView
):
    model = BookInstance
    template_name = 'library/user_bookinstance_delete.html'
    success_url = reverse_lazy('user_book_instances')

    def form_valid(self, form):
        messages.success(self.request, _('Book is now returned.'))
        return super().form_valid(form)

    def test_func(self) -> bool | None:
        obj = self.get_object()
        return obj.reader == self.request.user

ptu12_library/library/templates/library/author_detail.html
{% extends 'base.html' %}
{% block title %}{{ author }} | {{ block.super }}{% endblock title %}
{% block content %}
<h1>{{ author }}</h1>
{{ author.biography|safe }}
{% if author.books.all.count > 0 %}
<h2>{{ author.last_name }}'s books in our library</h2>
<ul>
    {% for book in author.books.all %}
        <li><a href="{% url 'book_detail' book.pk %}">{{ book.title }}</a></li>
    {% endfor %}
</ul>
{% endif %}
{% endblock content %}

ptu12_library/library/templates/library/authors.html
{% extends 'base.html' %}
{% block title %}Authors in {{ block.super }}{% endblock title %}
{% block content %}
<h1>Authors</h1>
{% include 'includes/search.html' %}
{% if author_list %}
{% with author_list as page_obj %}
    {% include 'includes/paginator_nav.html' %}
{% endwith %}
<ul>
    {% for author in author_list %}
        <li><a href="{% url 'author_detail' author.pk %}">{{ author }}</a>
        {% comment %} {% if author.books.all.count > 0 %}
        <ul>
            {% for book in author.books.all %}
                <li>{{ book.title }}</li>
            {% endfor %}
        </ul>
        {% endif %} {% endcomment %}
        </li>
    {% endfor %}
</ul>
{% with author_list as page_obj %}
    {% include 'includes/paginator_pages.html' %}
{% endwith %}
{% else %}
    <p>No authors found</p>
{% endif %}
{% endblock content %}

ptu12_library/library/templates/library/book_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ book.title }} | {{ block.super }}{% endblock title %}
{% block content %}
<h1>{{ book.title }}<a class="button float-right" href="{% url 'bookinstance_create' %}?book_id={{ book.id }}">Reserve</a></h1>
{% if book.cover %}
    <img class="book-cover" src="{{ book.cover.url }}">
{% else %}
    <img class="book-cover" src="{% static 'library/img/default_cover.jpg' %}">
{% endif %}
<h3>by <a href="{% url 'author_detail' book.author.pk %}">{{ book.author }}</a></h3>
{% if book.genre.count > 0 %}
    <p>Genre(s):
        {% for genre in book.genre.all %}
            <span class="book-genre">{{ genre }}</span>
        {% endfor %}
    </p>
{% endif %}
<h2>Summary</h2>
{{ book.summary|safe }}
{% if book.instances.count > 0 %}
    <h2>Copies</h2>
    <ul>
        {% for copy in book.instances.all %}
            <li class="book-status-{{ copy.status }}">{{ copy.get_status_display }}{% if copy.due_back %}, should be available {{ copy.due_back }}{% endif %}<span class="book-instance-id">{{ copy.id }}</span></li>
        {% endfor %}
    </ul>
{% endif %}
<h2>Reviews</h2>
{% if user.is_authenticated %}
    <form method="post" action="{{ request.path }}">
    <h3>Leave your review</h3>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Post</button>
    </form>
{% else %}
    <p class="box box-info">If you want to post a review, you have to <a href="{% url 'login' %}">login</a> or <a href="{% url 'signup' %}">sing up</a></p>
{% endif %}
{% if book.reviews.count > 0 %}
    <ul>
        {% for review in book.reviews.all %}
            <li>{{ review.reviewed_at }} by <a href="{% url 'profile' review.reviewer.id %}">
                {% if review.reviewer.profile.picture %}
                    <img src="{{ review.reviewer.profile.picture.url }}" class="user-avatar">
                {% endif %}
                {{ review.reviewer }}</a><br>
                {{ review.content }}
            </li>
        {% endfor %}
    </ul>
{% endif %}
{% endblock content %}

ptu12_library/library/templates/library/book_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Books in {{ block.super }}{% endblock title %}
{% block content %}
<h1>Books in PTU12 Library</h1>
{% include 'includes/search.html' %}
{% if book_list %}
{% include 'includes/paginator_nav.html' %}
<ul class="book-list">
    {% for book in book_list %}
        <li>
            <a href="{% url 'book_detail' book.pk %}">
                {% if book.cover %}
                    <img class="book-cover" src="{{ book.cover.url }}">
                {% else %}
                    <img class="book-cover" src="{% static 'library/img/default_cover.jpg' %}">
                {% endif %}
                <h3>
                    {% if book.title|length > 36 %}
                        {{ book.title|slice:35 }}...
                    {% else %}
                        {{ book.title }}
                    {% endif %}
                </h3>
            </a>
            <p>by <a href="{% url 'author_detail' book.author.pk %}">{{ book.author }}</a></p>
        </li>
    {% endfor %}
</ul>
{% include 'includes/paginator_pages.html' %}
{% else %}
<p>No books found</p>
{% endif %}
{% endblock content %}

ptu12_library/library/templates/library/bookinstance_form.html
{% extends 'base.html' %}
{% block title %}{% if taking %}Take{% elif extending %}Extend{% else %}Reserve{% endif %} {{ book.title }} at {{ block.super }}{% endblock title %}
{% block content %}
<h1>{% if taking %}Take{% elif extending %}Extend{% else %}Reserve{% endif %} a copy of {{ book.title }} by {{ book.author }}</h1>
<form method="post" action="{{ request.path }}?book_id={{ book.id }}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Confirm {% if taking %}Borrowing{% elif extending %}Extension{% else %}Reservation{% endif %}</button>
</form>
{% endblock content %}

ptu12_library/library/templates/library/index.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}Welcome to {{ block.super }}{% endblock title %}
{% block content %}
<h1>PTU12 Library</h1>
<p>Welcome to book paradise!</p>
<p>Currently available:</p>
<ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Book Copies:</strong> {{ num_instances }}</li>
    <li><strong>Available Copies:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li>You're visiting us already for the <strong>{{ num_visits|ordinal }}</strong> time</li>
</ul>
{% endblock content %}

ptu12_library/library/templates/library/user_bookinstance_delete.html
{% extends 'base.html' %}
{% block title %}Returning {{ object.book }} to {{ block.super }}{% endblock title %}
{% block content %}
<h1>Confirm Returning Book</h1>
<p>Title: {{ object.book.title }}</p>
<p>Author: {{ object.book.author }}</p>
<p>Copy ID: {{ object.id }}</p>
<p class="{% if object.is_overdue %}book-overdue{% endif %}">Due date: {{ object.due_back }}</p>
<form action="{{ request.path }}" method="post">
    {% csrf_token %}
    <button type="submit">Confirm Return</button>
    <a href="{% url 'user_book_instances' %}">Change my mind</a>
</form>
{% endblock content %}

ptu12_library/library/templates/library/user_bookinstance_list.html
{% extends 'base.html' %}
{% block title %}My Book at {{ block.super }}{% endblock title %}
{% block content %}
<h1>My borrowed books</h1>
{% if bookinstance_list %}
{% include 'includes/paginator_nav.html' %}
<ul>
    {% for copy in bookinstance_list %}
        <li class="book-status-{{ copy.status }}">
            {% if copy.status > 0 and copy.status < 3 %}
                <a class="button" href="{% url 'bookinstance_update' copy.pk %}">
                    {% if copy.status == 1 %}Take{% else %}Extend{% endif %}
                </a>
                {% if copy.status == 2 %}
                <a class="button box-success" href="{% url 'bookinstance_delete' copy.pk %}">Return</a>
                {% endif %}
            {% endif %}
            <a href="{% url 'book_detail' copy.book.pk %}">{{ copy.book.title }}</a>
            {{ copy.get_status_display }}{% if copy.due_back %}, return by {{ copy.due_back }}{% endif %}
            {% if copy.status == 2 and copy.is_overdue %}<span class="book-overdue">OVERDUE!</span>{% endif %}
            <span class="book-instance-id">{{ copy.id }}</span>
        </li>
    {% endfor %}
</ul>
{% include 'includes/paginator_pages.html' %}
{% else %}
<p class="box box-warning">
    Book borrowing history is still empty. Take some books!
</p>
{% endif %}
{% endblock content %}